'use strict';
const $ = selector => document.querySelector(selector);
const form=$('#composer'), input=$('#message'), sendButton=$('#sendButton'), scroller=$('#chat'), content=$('#chatContent');
const sidebar=$('#sidebar'), shell=$('.app-shell'), workspace=$('.workspace'), panel=$('#toolPanel'), panelBody=$('#panelBody');
const STORAGE_KEY='matchorakel-conversations-v1', FAVORITES_KEY='matchorakel-favorites-v1';
const LEAGUE_NAMES={PL:'Premier League',LL:'La Liga',BL:'Bundesliga',SA:'Serie A',L1:'Ligue 1',UCL:'Champions League',FAC:'FA Cup',CDR:'Copa del Rey',EL:'Europa League',UECL:'Conference League',DFB:'DFB-Pokal',CIT:'Coppa Italia'};
const arrow='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 19V5m0 0-6 6m6-6 6 6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const uid=()=>crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36)+Math.random().toString(36).slice(2);
function element(tag,cls='',text){const el=document.createElement(tag);el.className=cls;if(typeof text==='string'||typeof text==='number')el.textContent=String(text);return el;}
function button(text,cls,handler){const b=element('button',cls,text);b.type='button';b.addEventListener('click',handler);return b;}
function announce(text){$('#announcer').textContent=text;}
function readJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
function writeJSON(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{announce('Lagringen är full eller avstängd. Chatten sparas bara i den här fliken.');return false;}}
function oldAnswer(turn){return turn.answer||turn.data&&{...turn.data,kind:'prediction'}||turn.insight&&{...turn.insight,kind:'insight'}||turn.fixtures&&{...turn.fixtures,kind:'fixtures'}||turn.combined&&{...turn.combined,kind:'combined'}||turn.text&&{kind:'text',response:turn.text,context:turn.context,topic_reset:turn.topicReset}||null;}
function readConversations(){const raw=readJSON(STORAGE_KEY,[]);return Array.isArray(raw)?raw.filter(c=>c&&typeof c.id==='string'&&typeof c.title==='string'&&Array.isArray(c.messages)).slice(0,30).map(c=>({...c,messages:c.messages.filter(t=>t&&typeof t.question==='string').slice(-100).map(t=>({...t,id:t.id||uid(),answer:oldAnswer(t),error:t.error||(!oldAnswer(t)?'Svaret blev avbrutet.':null)}))})):[];}
let conversations=readConversations(),activeId=history.state?.chatId||conversations[0]?.id||null,pending=null,panelRequest=null,undoTimer;
let favorites=readJSON(FAVORITES_KEY,[]);if(!Array.isArray(favorites))favorites=[];favorites=favorites.filter(x=>typeof x==='string');
const favoriteKey=name=>String(name).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\b(fc|cf)\b/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const current=()=>conversations.find(c=>c.id===activeId);
function save(){writeJSON(STORAGE_KEY,conversations.slice(0,30).map(c=>({...c,messages:c.messages.slice(-100)})));}
function nearBottom(){return scroller.scrollHeight-scroller.clientHeight-scroller.scrollTop<80;}
function scrollBottom(smooth=false){scroller.scrollTo({top:scroller.scrollHeight,behavior:smooth&&!reduced.matches?'smooth':'instant'});$('#scrollBottom').hidden=true;}
scroller.addEventListener('scroll',()=>{$('#scrollBottom').hidden=nearBottom()||!current()?.messages.length;},{passive:true});
$('#scrollBottom').addEventListener('click',()=>scrollBottom(true));
function syncInput(){input.style.height='44px';input.style.height=Math.min(200,Math.max(44,input.scrollHeight))+'px';input.style.overflowY=input.scrollHeight>200?'auto':'hidden';sendButton.disabled=!pending&&!input.value.trim();sendButton.type=pending?'button':'submit';sendButton.setAttribute('aria-label',pending?'Stoppa svar':'Skicka fråga');sendButton.innerHTML=pending?'<span class="stop-square" aria-hidden="true"></span>':arrow;}
input.addEventListener('input',syncInput);
input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&e.keyCode!==229){e.preventDefault();if(!pending)form.requestSubmit();}});
sendButton.addEventListener('click',()=>{if(pending)stopRequest();});
function setSidebar(open){const mobile=matchMedia('(max-width:720px)').matches;if(mobile){sidebar.classList.toggle('open',open);$('#scrim').hidden=!open;sidebar.inert=!open;}else{shell.classList.toggle('sidebar-collapsed',!open);sidebar.inert=!open;$('#scrim').hidden=true;}$('#openSidebar').setAttribute('aria-expanded',String(open));}
$('#openSidebar').addEventListener('click',()=>setSidebar($('#openSidebar').getAttribute('aria-expanded')!=='true'));
$('#closeSidebar').addEventListener('click',()=>{setSidebar(false);$('#openSidebar').focus();});$('#scrim').addEventListener('click',()=>setSidebar(false));
function closeMobile(){if(matchMedia('(max-width:720px)').matches)setSidebar(false);}
function switchChat(id,record=true){stopRequest(false);activeId=conversations.some(c=>c.id===id)?id:null;if(record)history.pushState({chatId:activeId},'');render();closeMobile();input.focus();}
function newChat(){switchChat(null);input.value='';syncInput();}
$('#newChat').addEventListener('click',newChat);$('#brandHome').addEventListener('click',newChat);
window.addEventListener('popstate',e=>switchChat(e.state?.chatId||null,false));
function historyGroup(chat){const stamp=new Date(chat.updatedAt||chat.createdAt||Number(chat.id.split('-')[0])||0);const today=new Date();today.setHours(0,0,0,0);const yesterday=new Date(today);yesterday.setDate(today.getDate()-1);return stamp>=today?'Idag':stamp>=yesterday?'Igår':'Tidigare';}
function deleteChat(chat){if(pending?.chatId===chat.id)stopRequest(false);conversations=conversations.filter(c=>c.id!==chat.id);if(activeId===chat.id)activeId=conversations[0]?.id||null;save();render();const toast=$('#undoToast');toast.hidden=false;toast.replaceChildren(element('span','','Chatten raderades.'),button('Ångra','',()=>{if(!conversations.some(c=>c.id===chat.id))conversations.unshift(chat);activeId=chat.id;save();render();toast.hidden=true;clearTimeout(undoTimer);}));clearTimeout(undoTimer);undoTimer=setTimeout(()=>toast.hidden=true,8000);}
function renderSidebar(){const nav=$('#conversations');nav.replaceChildren();const query=$('#searchConversations').value.trim().toLocaleLowerCase('sv');const filtered=conversations.filter(c=>(c.title+' '+c.messages.map(t=>t.question).join(' ')).toLocaleLowerCase('sv').includes(query));for(const group of ['Idag','Igår','Tidigare']){const chats=filtered.filter(c=>historyGroup(c)===group);if(!chats.length)continue;nav.append(element('h2','history-group',group));for(const chat of chats){const row=element('div','conversation-row'+(chat.id===activeId?' active':''));const title=button(chat.title,'conversation',()=>switchChat(chat.id));if(chat.id===activeId)title.setAttribute('aria-current','page');const more=button('…','conversation-more',()=>{const old=row.querySelector('.conversation-menu');document.querySelectorAll('.conversation-menu').forEach(n=>n.remove());if(old)return;const menu=element('div','conversation-menu');menu.append(button('Ta bort','',()=>deleteChat(chat)));row.append(menu);menu.querySelector('button').focus();});more.setAttribute('aria-label','Alternativ för '+chat.title);row.append(title,more);nav.append(row);}}
if(query&&!filtered.length)nav.append(element('p','empty-history','Ingen chatt matchar sökningen.'));}
$('#searchConversations').addEventListener('input',renderSidebar);
document.addEventListener('click',e=>{if(!e.target.closest('.conversation-row'))document.querySelectorAll('.conversation-menu').forEach(n=>n.remove());});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(panel.open)return;document.querySelectorAll('.conversation-menu').forEach(n=>n.remove());if(sidebar.classList.contains('open')){setSidebar(false);$('#openSidebar').focus();}}if(e.key==='Tab'&&sidebar.classList.contains('open')&&!panel.open){const items=[...sidebar.querySelectorAll('button,a,input')].filter(n=>!n.hidden&&n.offsetParent!==null);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
function fixtureDate(f,language="sv"){const d=new Date(f.utc_date);if(Number.isNaN(d.getTime()))return 'Datum saknas';const confirmed=f.kickoff_confirmed??['TIMED','IN_PLAY','PAUSED','FINISHED'].includes(f.status);return new Intl.DateTimeFormat(language==='en'?'en-GB':'sv-SE',{timeZone:confirmed?'Europe/Stockholm':'UTC',day:'numeric',month:'long',year:'numeric',...(confirmed?{hour:'2-digit',minute:'2-digit'}:{})}).format(d)+(confirmed?(language==='en'?' · Stockholm time':' · svensk tid'):(language==='en'?' · kickoff time unconfirmed':' · avspark inte fastställd'));}
function venueText(f,language="sv"){return typeof f.venue==='string'&&f.venue.trim()?(f.venue_confidence==='likely_home'?(language==='en'?'Likely home venue: ':'Trolig hemmaarena: '):'')+f.venue:(language==='en'?'Venue unavailable from source':'Arena saknas i källan');}
function renderFixture(f,language="sv"){const box=element('div','fixture-card');box.append(element('div','fixture-pair',`${f.home} – ${f.away}`),element('div','fixture-date',fixtureDate(f,language)),element('div','fixture-venue',venueText(f,language)));if(f.status==='FINISHED'&&Number.isInteger(f.score?.home)&&Number.isInteger(f.score?.away))box.append(element('div','',`Resultat: ${f.score.home}–${f.score.away}`));if(typeof f.source==='string'){const note=element('div','fixture-source',f.source+(typeof f.synced_at==='string'&&Number.isFinite(Date.parse(f.synced_at))?' · hämtat '+f.synced_at.slice(0,10):''));box.append(note);}return box;}
function answerText(a){if(!a)return '';if(a.response)return a.response;if(a.kind==='combined')return(a.parts||[]).map(answerText).join('\n');if(a.kind==='prediction'&&a.scoreline)return `Prediction: ${a.home} ${a.scoreline.home}–${a.scoreline.away} ${a.away}. Hemmaseger ${a.probabilities?.H} %, oavgjort ${a.probabilities?.D} %, bortaseger ${a.probabilities?.A} %.`;if(a.kind==='fixtures')return (a.summary||'')+'\n'+(a.fixtures||[]).map(f=>`${f.home} – ${f.away}: ${fixtureDate(f)}. ${venueText(f)}.`).join('\n');if(a.kind==='insight')return [a.title,a.summary,...(a.cards||[]).map(c=>`${c.label}: ${c.value}. ${c.detail||''}`)].filter(Boolean).join('\n');return '';}
function validAnswer(a,depth=0){if(!a||typeof a!=='object'||depth>3)return false;if(a.kind==='error')return typeof a.error==='string';if(a.kind==='text')return typeof a.response==='string'&&a.response.trim().length>0;if(a.kind==='prediction'){const p=a.probabilities;return p&&['H','D','A'].every(k=>typeof p[k]==='number'&&Number.isFinite(p[k])&&p[k]>=0&&p[k]<=100)&&Math.abs(p.H+p.D+p.A-100)<1&&['home','away'].every(k=>typeof a[k]==='string'&&Number.isInteger(a.scoreline?.[k])&&a.scoreline[k]>=0&&a.scoreline[k]<=10);}if(a.kind==='fixtures')return Array.isArray(a.fixtures)&&a.fixtures.length>0&&a.fixtures.every(f=>f&&typeof f.home==='string'&&typeof f.away==='string'&&Number.isFinite(Date.parse(f.utc_date)));if(a.kind==='insight')return typeof a.title==='string'&&Array.isArray(a.cards)&&a.cards.every(c=>c&&typeof c.label==='string'&&['string','number'].includes(typeof c.value));if(a.kind==='combined')return Array.isArray(a.parts)&&a.parts.length>0&&a.parts.every(p=>validAnswer(p,depth+1));return false;}
function renderAnswer(a,container){if(!validAnswer(a)){container.append(element('p','error-response','Svaret kunde inte läsas.'));return;}if(a.kind==='combined'){a.parts.forEach((part,i)=>{const block=element('div',i?'combined-part':'');renderAnswer(part,block);container.append(block);});return;}
if(a.response)container.append(element('p',a.kind==='prediction'?'prediction-line':'answer-text',a.response));
if(a.kind==='prediction'){if(!a.response)container.append(element('p','prediction-line',answerText(a)));const row=element('div','outcomes');const p=a.probabilities,best=Math.max(p.H,p.D,p.A);for(const[key,label]of[['H',a.home],['D',a.language==='en'?'Draw':'Oavgjort'],['A',a.away]]){const block=element('div','outcome'+(p[key]===best?' best':''));block.append(element('div','outcome-label',label),element('div','outcome-number',`${p[key].toLocaleString(a.language==='en'?'en':'sv-SE')} %`));const track=element('div','outcome-track'),fill=element('div','outcome-fill');fill.style.width=p[key]+'%';track.append(fill);block.append(track);row.append(block);}container.append(row);if(a.explanation)container.append(element('p','answer-text',a.explanation));const details=element('details','details-toggle');details.append(element('summary','',a.language==='en'?'Data and method':'Underlag och metod'));details.append(element('p','',`${a.model||'Målmodell'} · ${a.as_of||''}`),element('p','',a.scoreline.source||''));if(a.fixture)details.append(renderFixture(a.fixture,a.language));container.append(details);if(a.fixture)resultCheck(a,container);}
else if(a.kind==='fixtures'){if(a.summary&&!a.response)container.append(element('p','answer-text',a.summary));for(const f of a.fixtures)container.append(renderFixture(f,a.language));}
else if(a.kind==='insight'&&!a.response){container.append(element('h2','result-title',a.title));if(a.summary)container.append(element('p','answer-text',a.summary));for(const c of a.cards){const box=element('div','insight-card');box.append(element('span','insight-label',c.label),element('span','insight-value',c.value));if(c.detail)box.append(element('div','insight-detail',c.detail));container.append(box);}}
}
function resultCheck(a,container){const btn=button('Kontrollera resultat','result-check',async()=>{btn.disabled=true;const original=btn.textContent;try{const q=new URLSearchParams({league:a.league,home:a.home,away:a.away,date:a.fixture.utc_date});const r=await fetchJSON('/api/match/result?'+q);btn.textContent=r.status==='finished'?`Resultat: ${r.home_goals}–${r.away_goals}`:r.status==='not_played'?'Matchen är inte spelad ännu':'Resultat saknas – försök igen';}catch{btn.textContent='Kunde inte hämta – försök igen';}finally{btn.disabled=false;btn.setAttribute('aria-label',btn.textContent||original);}});container.append(btn);}
function turnNode(turn,animate=false){const node=element('article','turn');node.dataset.turnId=turn.id;node.append(element('div','question'+(animate?' new-message':''),turn.question));const response=element('div','response');if(turn.error){response.setAttribute('role','alert');response.append(element('p','error-response',turn.error),button('Försök igen','retry-button',()=>submitQuestion(turn.question,turn)));}else if(turn.answer){renderAnswer(turn.answer,response);const actions=element('div','response-actions');actions.append(button('Kopiera','copy-button',async e=>{const target=e.currentTarget;try{await navigator.clipboard.writeText(answerText(turn.answer));target.textContent='Kopierat';}catch{announce('Kopiering stöds inte här. Markera texten och kopiera.');}}));response.append(actions);}else{response.append(element('div','loading-dot'));response.setAttribute('aria-label','Väntar på svar');}node.append(response);return node;}
function updateTurn(turn){const old=[...content.children].find(n=>n.dataset.turnId===turn.id);const follow=nearBottom();if(old){const fresh=turnNode(turn);old.querySelector('.response').replaceWith(fresh.querySelector('.response'));old.querySelector('.response').classList.add('new-message');}if(follow)scrollBottom();renderFollowup();}
function renderFollowup(){const host=$('#followups');host.replaceChildren();const last=current()?.messages.at(-1);if(!last?.answer||pending)return;const suggestion=last.answer.suggestions?.find(x=>typeof x==='string');if(suggestion)host.append(button(suggestion,'followup',()=>submitQuestion(suggestion)));}
function render(){content.replaceChildren();const chat=current();workspace.classList.toggle('is-empty',!chat?.messages.length);chat?.messages.forEach(t=>content.append(turnNode(t)));renderSidebar();renderFollowup();syncInput();requestAnimationFrame(()=>scrollBottom());}
function conversationContext(chat){for(const t of [...chat.messages].reverse()){if(t.answer?.topic_reset)return null;if(t.answer?.context)return t.answer.context;}return null;}
async function fetchJSON(url,options={}){const ctrl=new AbortController(),abort=()=>ctrl.abort(),timer=setTimeout(abort,20000);options.signal?.addEventListener('abort',abort,{once:true});if(options.signal?.aborted)abort();try{const r=await fetch(url,{...options,signal:ctrl.signal});const data=await r.json();if(!r.ok)throw new Error(data.error||`Anropet misslyckades (${r.status}).`);return data;}finally{clearTimeout(timer);options.signal?.removeEventListener('abort',abort);}}
function stopRequest(redraw=true,persist=true){const old=pending;if(!old)return;pending=null;old.controller.abort();clearTimeout(old.timer);old.turn.error='Svaret stoppades.';old.turn.answer=null;fetch('/api/chat/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request_id:old.id}),keepalive:true}).catch(()=>{});if(persist)save();syncInput();if(redraw&&activeId===old.chatId)updateTurn(old.turn);}
async function submitQuestion(value,retryTurn=null){const question=value.trim();if(!question||pending)return;if(question.length>2000){announce('Skriv högst 2 000 tecken.');return;}let chat=current();if(!chat){chat={id:uid(),title:question.slice(0,65),createdAt:Date.now(),updatedAt:Date.now(),messages:[]};conversations.unshift(chat);activeId=chat.id;history.replaceState({chatId:activeId},'');}
const previousTurns=retryTurn?chat.messages.slice(0,chat.messages.indexOf(retryTurn)):chat.messages;
const previousContext=conversationContext({...chat,messages:previousTurns});const prior=previousTurns.filter(t=>t.answer&&!t.error).slice(-8).map(t=>({question:t.question,answer:answerText(t.answer)}));
const turn=retryTurn||{id:uid(),question};turn.answer=null;turn.error=null;if(!retryTurn)chat.messages.push(turn);chat.updatedAt=Date.now();const requestId=uid(),controller=new AbortController();const operation={id:requestId,chatId:chat.id,controller,turn};pending=operation;
operation.timer=setTimeout(()=>{if(pending===operation){stopRequest();turn.error='Svaret tog för lång tid. Försök igen.';save();if(activeId===chat.id)updateTurn(turn);}},60000);
const wasEmpty=workspace.classList.contains('is-empty');const before=$('.composer-area').getBoundingClientRect();workspace.classList.remove('is-empty');input.value='';syncInput();if(retryTurn)updateTurn(turn);else content.append(turnNode(turn,true));renderSidebar();renderFollowup();if(wasEmpty&&!reduced.matches){const after=$('.composer-area').getBoundingClientRect();$('.composer-area').animate([{transform:`translateY(${before.top-after.top}px)`},{transform:'translateY(0)'}],{duration:280,easing:'cubic-bezier(.2,0,0,1)'});}scrollBottom();save();
try{const response=await fetch('/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:question,context:previousContext,history:prior,request_id:requestId}),signal:controller.signal});const data=await response.json();if(pending!==operation||!conversations.some(c=>c.id===chat.id))return;if(!response.ok||data.kind==='error')throw new Error(data.error||'Svaret kunde inte hämtas.');if(!validAnswer(data))throw new Error('Servern skickade ett ofullständigt svar.');turn.answer=data;turn.error=null;}
catch(error){if(pending!==operation)return;turn.error=error.name==='AbortError'?'Svaret avbröts.':navigator.onLine?(error instanceof TypeError?'Anslutningen bröts. Försök igen.':error.message):'Du är offline. Anslut till internet och försök igen.';}
finally{clearTimeout(operation.timer);if(pending===operation){pending=null;save();syncInput();if(activeId===chat.id){updateTurn(turn);announce(turn.error||'Svar klart.');}}}}
form.addEventListener('submit',e=>{e.preventDefault();submitQuestion(input.value);});
function panelOpen(title){panelRequest?.abort();panelRequest=new AbortController();$('#panelTitle').textContent=title;panelBody.replaceChildren();if(!panel.open)panel.showModal();return panelRequest;}
function closePanel(){panelRequest?.abort();panelRequest=null;panel.close();}$('#closePanel').addEventListener('click',closePanel);panel.addEventListener('cancel',()=>{panelRequest?.abort();panelRequest=null;});panel.addEventListener('click',e=>{if(e.target===panel){const r=panel.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closePanel();}});
function panelError(message,retry){panelBody.replaceChildren(element('p','error-response',message),button('Försök igen','panel-action',retry));}
function skeleton(){panelBody.append(element('div','loading-skeleton'),element('div','loading-skeleton short'));}
async function showMatches(){const op=panelOpen('Matcher och favoritlag');skeleton();try{const raw=await fetchJSON('/api/fixtures',{signal:op.signal});if(panelRequest!==op)return;if(!Array.isArray(raw))throw Error('Schemat kunde inte läsas.');const fixtures=raw.filter(f=>f&&typeof f.home==='string'&&typeof f.away==='string'&&Number.isFinite(Date.parse(f.utc_date)));panelBody.replaceChildren();const select=element('select','panel-select');select.setAttribute('aria-label','Tävling');for(const[k,v]of Object.entries({all:'Alla tävlingar',favorites:'Favoritlag',...LEAGUE_NAMES})){const o=element('option','',v);o.value=k;select.append(o);}const search=element('input','panel-input');search.placeholder='Sök lag';search.setAttribute('aria-label','Sök lag');const list=element('div','match-list');let limit=6;
function draw(){list.replaceChildren();const q=favoriteKey(search.value);const selected=fixtures.filter(f=>(select.value==='all'||select.value===f.league||select.value==='favorites'&&[f.home,f.away].some(t=>favorites.includes(favoriteKey(t))))&&favoriteKey(f.home+' '+f.away).includes(q));if(!selected.length)list.append(element('p','panel-muted',select.value==='favorites'?'Inga kommande matcher för dina favoritlag.':'Inga matcher hittades i det hämtade schemat.'));for(const f of selected.slice(0,limit)){const row=element('div','match-row');row.append(element('div','match-row-teams',`${f.home} – ${f.away}`),element('div','match-row-date',fixtureDate(f)),element('div','match-row-venue',venueText(f)));const actions=element('div','match-row-actions');for(const team of [f.home,f.away]){const key=favoriteKey(team),chosen=favorites.includes(key);const fav=button((chosen?'Följer ':'Följ ')+team,'favorite-button',()=>{favorites=favorites.includes(key)?favorites.filter(x=>x!==key):[...favorites,key];writeJSON(FAVORITES_KEY,favorites);draw();});fav.setAttribute('aria-pressed',String(chosen));actions.append(fav);}actions.append(button('Fråga om matchen','panel-ask',()=>{closePanel();closeMobile();submitQuestion(`${f.home} mot ${f.away} i ${LEAGUE_NAMES[f.league]||f.league}, när spelas matchen?`);}));row.append(actions);list.append(row);}if(selected.length>limit)list.append(button('Visa fler','panel-action',()=>{limit+=6;draw();}));}
select.addEventListener('change',()=>{limit=6;draw();});search.addEventListener('input',()=>{limit=6;draw();});panelBody.append(select,search,list);draw();}catch(e){if(panelRequest===op&&!op.signal.aborted)panelError(e.message,showMatches);}}
$('#openMatches').addEventListener('click',showMatches);
async function showAbout(){const op=panelOpen('Om Matchorakel');panelBody.append(element('p','','Matchprognoser och statistik för '+Object.values(LEAGUE_NAMES).slice(0,5).join(', ')+'.'),element('p','','Cupmatcher: '+Object.values(LEAGUE_NAMES).slice(5).join(', ')+'. Scheman beror på datakällans åtkomst. Cupanalyser bygger på ligahistorik.'),element('p','panel-muted','Matchdata: football-data.co.uk och football-data.org. Chattar sparas i den här webbläsaren.'));try{const status=await fetchJSON('/api/chat/status',{signal:op.signal});if(panelRequest===op)panelBody.append(element('p','panel-muted',status.ai_health==='ok'?'Gemini svarade på det senaste kontrollerade anropet.':status.ai_health==='unconfigured'?'Gemini är inte konfigurerad på servern.':'Gemini: '+({unverified:'ännu inte testad',failed:'senaste anropet misslyckades'}[status.ai_health]||'status saknas')+'.'));}catch{if(panelRequest===op)panelBody.append(element('p','panel-muted','Anslutningsstatus kunde inte hämtas.'));}}
$('#openAbout').addEventListener('click',showAbout);
async function showDataStatus(){const op=panelOpen('Uppdatera data');skeleton();try{const state=await fetchJSON('/api/data/status',{signal:op.signal});if(panelRequest!==op)return;panelBody.replaceChildren();for(const record of Object.values(state.leagues||{}))panelBody.append(element('div','panel-data-row',`${record.name}: ${record.trained?'modell finns':'modell saknas'}, ${record.files} matchfiler`));panelBody.append(element('p','panel-muted',state.job?.message||'Ingen uppdatering pågår.'));const token=element('input','panel-input');token.type='password';token.autocomplete='new-password';token.placeholder='Datanyckel (endast för spelschema)';token.setAttribute('aria-label','football-data.org-nyckel');panelBody.append(token);for(const[k,label]of[['fixtures','Uppdatera spelschema'],['results','Uppdatera resultat och modeller']]){const b=button(label,'panel-action',async()=>{b.disabled=true;try{await fetchJSON('/api/data/update',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:k,token:token.value})});token.value='';showDataStatus();}catch(e){if(panelRequest===op){panelBody.append(element('p','error-response',e.message));b.disabled=false;}}});b.disabled=!!state.job?.running;panelBody.append(b);}if(state.job?.running)setTimeout(()=>{if(panelRequest===op&&panel.open)showDataStatus();},3000);}catch(e){if(panelRequest===op&&!op.signal.aborted)panelError(e.message,showDataStatus);}}
$('#openData').addEventListener('click',showDataStatus);
window.addEventListener('storage',e=>{if(e.key===STORAGE_KEY){stopRequest(false,false);clearTimeout(undoTimer);$('#undoToast').hidden=true;conversations=readConversations();if(!current())activeId=null;render();announce('Chatthistoriken uppdaterades från en annan flik.');}else if(e.key===FAVORITES_KEY){const v=readJSON(FAVORITES_KEY,[]);favorites=Array.isArray(v)?v.filter(x=>typeof x==='string'):[];}});
window.addEventListener('pagehide',()=>stopRequest(false));
function viewport(){if(window.visualViewport)document.documentElement.style.setProperty('--app-height',window.visualViewport.height+'px');}
window.visualViewport?.addEventListener('resize',viewport);viewport();matchMedia('(max-width:720px)').addEventListener('change',e=>setSidebar(!e.matches));setSidebar(!matchMedia('(max-width:720px)').matches);
if(!current())activeId=null;history.replaceState({chatId:activeId},'');render();fetchJSON('/api/chat/status').then(s=>{$('#openData').hidden=s.public!==false;}).catch(()=>{});
